# Generated by Django 4.1.13 on 2024-08-20 17:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorias', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoria',
            name='tema',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BEC', 'Becas'), ('INS', 'Inscripción'), ('ING', 'Inglés'), ('ORG', 'Órgano colegiado'), ('REG', 'Reglamentos'), ('SS', 'Servicio Social'), ('MOV', 'Movilidad'), ('PT', 'Proyecto Terminal'), ('EV', 'Estancia de Verano'), ('TC', 'Trayectoria Curricular'), ('EG', 'Eleccion de grupo'), ('TIT', 'Titulación'), ('EGRE', 'Egreso'), ('PER', 'Personales'), ('SR', 'Seguimiento de reunión'), ('OTRO', 'Otro')], default='SS', max_length=4, verbose_name='SS'), size=None),
        ),
    ]
