# Generated by Django 4.1.13 on 2024-11-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorias', '0003_alter_tutoria_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('archivo', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
