# Generated by Django 4.1.13 on 2025-02-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorias', '0003_alter_tutoria_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoria',
            name='asesoria_especializada',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='tutoria',
            name='asistencia',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='tutoria',
            name='beca_otorgada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tutoria',
            name='duracion',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=[(0, 'Menos de 30 minutos'), (1, '30 minutos'), (2, '1 hora'), (3, '2 horas'), (4, 'Más de dos horas')]),
        ),
        migrations.AddField(
            model_name='tutoria',
            name='firma_documentos_beca',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='tutoria',
            name='impacto_tutoria',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tutoria',
            name='observaciones',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tutoria',
            name='resultados_tutoria',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
