# Generated by Django 4.1.13 on 2025-03-11 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorias', '0004_plantilla'),
        ('Tutorias', '0004_tutoria_asesoria_especializada_tutoria_asistencia_and_more'),
    ]

    operations = [
    ]
