# Generated by Django 4.1.13 on 2024-09-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='estado',
            field=models.IntegerField(choices=[('', 'Selecciona un estado'), (1, 'Activo'), (2, 'No reinscrito'), (10, 'Inscrito sin carga académica')], null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('', 'Seleccione un sexo'), ('M', 'Masculino'), ('F', 'Femenino')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='carrera',
            field=models.CharField(choices=[('', 'Seleccione una'), ('MAT', 'Matemáticas Aplicadas'), ('COM', 'Ingeniería en Computación')], max_length=30),
        ),
        migrations.AlterField(
            model_name='coda',
            name='coordinacion',
            field=models.CharField(choices=[('', 'Seleccione una'), ('MAT', 'Matemáticas Aplicadas'), ('COM', 'Ingeniería en Computación')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cordinador',
            name='coordinacion',
            field=models.CharField(choices=[('', 'Seleccione una'), ('MAT', 'Matemáticas Aplicadas'), ('COM', 'Ingeniería en Computación')], max_length=30),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='coordinacion',
            field=models.CharField(choices=[('', 'Seleccione una'), ('MAT', 'Matemáticas Aplicadas'), ('COM', 'Ingeniería en Computación')], max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('', 'Seleccione Rol'), ('TUT', 'Tutor'), ('COR', 'Coordinador'), ('ALU', 'Alumno'), ('CODA', 'Coda')], default='USR', max_length=8),
        ),
    ]
