# Generated by Django 4.1.13 on 2025-02-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_alumno_estado_usuario_sexo_alter_alumno_carrera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cordinador',
            name='es_tutor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutor',
            name='es_tutor',
            field=models.BooleanField(default=True),
        ),
    ]
