# Generated by Django 4.1.13 on 2025-03-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_alumno_trimestre_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='second_last_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
