# Generated by Django 4.1.13 on 2025-02-08 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_cordinador_es_tutor_tutor_es_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cordinador',
            name='tutor_relacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cordinador_relacion', to='Usuarios.tutor'),
        ),
    ]
