# Generated by Django 4.1.13 on 2024-08-31 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_alter_alumno_carrera_alter_coda_coordinacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'No reinscrito'), (10, 'Inscrito sin carga académica')], null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('', 'Seleccione un sexo'), ('M', 'Masculino'), ('F', 'Femenino')], max_length=30, null=True),
        ),
    ]
