# Generated by Django 4.1.13 on 2025-02-12 01:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_cordinador_tutor_relacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('', 'Seleccione Rol'), ('TUT', 'Tutor'), ('COR', 'Coordinador'), ('ALU', 'Alumno'), ('CODA', 'Coda')], max_length=8), default=list, size=None),
        ),
    ]
