# Generated by Django 4.1.13 on 2025-03-11 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_documento'),
        ('Usuarios', '0005_alter_usuario_rol'),
    ]

    operations = [
    ]
