# Generated by Django 4.1.13 on 2025-03-21 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_usuario_second_last_name'),
        ('Usuarios', '0006_merge_0003_documento_0005_alter_usuario_rol'),
    ]

    operations = [
    ]
